// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWQqljiT7WNJcdFc89nObVKq6v-T8pEaQ',
    appId: '1:762207391010:web:ce97c317a1aea4ff65297b',
    messagingSenderId: '762207391010',
    projectId: 'nanapoc-7c5f9',
    authDomain: 'nanapoc-7c5f9.firebaseapp.com',
    storageBucket: 'nanapoc-7c5f9.firebasestorage.app',
    measurementId: 'G-RCK973DPVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAz1rtxLtwI0YSRAI6sM9tnaM8yYLp2nE',
    appId: '1:762207391010:android:2902d087b953882965297b',
    messagingSenderId: '762207391010',
    projectId: 'nanapoc-7c5f9',
    storageBucket: 'nanapoc-7c5f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3RLtN2ifNPcqDNrLCN_99KslYu7G1abE',
    appId: '1:762207391010:ios:4d9e92b1a0382f6065297b',
    messagingSenderId: '762207391010',
    projectId: 'nanapoc-7c5f9',
    storageBucket: 'nanapoc-7c5f9.firebasestorage.app',
    iosBundleId: 'com.example.nanaPoc',
  );
}
